### ISSUE TITLE
remotes

### ISSUE THREAD

**Issue by reergymerej** [reergymerej/start#5]
Since this is just sugar on Git cloning, can we support remote repos?  Do we want to?

**Comment by kondor6c** [comment]
perhaps you could just specify the URI and go from there, if the URI is remote then more power to you, if local the clone could behave the same way

**Comment by reergymerej** [comment]
Perhaps 82nd sucks!!!  What's up, dude?!

**Comment by reergymerej** [comment]
This is currently super lazy and assumes the template name is the name of a project in a local dir.  
`start-project hamandcheese sandwich-template` looks for `$TEMPLATE_DIR/sandwich-template`.

Maybe if it's not found locally, treat it as a remote url.

`start-project hamandcheese git@github.com:reergymerej/sandwich-template.git`

Then we'd need to tease out the name from the url for the `PROJECT_NAME` replacement step.

-OR-

`start-project hamandcheese sandwich-template`
* look in local dir
* look at $REMOTE_CRAP/sandwich-template.git

That's easier to do right off, but requires config (not supported yet) and prevents using `faulkners-template` if I don't have a fork.

Can symlinks point to a url?  🤔

**Comment by kondor6c** [comment]
> This is currently super lazy and assumes the template name is the name of a project in a local dir.
start-project hamandcheese sandwich-template looks for $TEMPLATE_DIR/sandwich-template
> Maybe if it's not found locally, treat it as a remote url.

It seemed like that each template was the project git repository, I think that's a great idea. I don't care what the project URI is, just give me one "file:///path/" or ssh:// if that fails then just fallback to doing a `cp`. Very cool stuff you have here! I think its pretty easy to tell if the URI is remote, and to just catch the failure based on the exit code. OR stat the file and if it fails try to fetch that? seems a little more messy though. But I think the ability to clone from a remote repository is too good to not utilize, since that's a method of bringing in other projects and collaborating
Here is just a sample (I'm sure you know, but others in the future might not)
```
kondor6c_0@horse:tmp$ git clone git@github.com:opencontainers/image-spec.git
Cloning into 'image-spec'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 3470 (delta 1), reused 7 (delta 1), pack-reused 3463
Receiving objects: 100% (3470/3470), 4.70 MiB | 7.16 MiB/s, done.
Resolving deltas: 100% (2036/2036), done.
kondor6c_0@horse:tmp$ git clone /home/kondor6c/repo/go_experiments/
Cloning into 'go_experiments'...
done.
```
> That's easier to do right off, but requires config (not supported yet) and prevents using faulkners-template if I don't have a fork

I thought config might be harder to do without a parsing tool like `jq` or a library that handles yaml/toml, etc. But yeah I think having an environment variable could work that's why I like to use the Bash substitution `${VAR:-default} if it isn't defined then default will be $VAR.  

> Can symlinks point to a url? 
Not to my knowledge :-( unless your cool with voodoo

keep up the good work, let me know how I can help. Even if it's spear throwing a broomstick from a 2nd story balcony ;-)

**Comment by reergymerej** [comment]
You seem much Bash-ier than me.  I look forward to you implementing everything while I watch.
